name: Deploy to Vercel

on:
  push:

concurrency:
  group: vercel-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: team_E0mJu3Lig78NlOFQfgP0GVZX
      VERCEL_PROJECT_ID: prj_GM0gqpeQtOh8Csj7n1pdxVhBfs1J
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel@60.0.0

      - name: Pull environment
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --scope manglekuo-s-team --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build
        run: vercel build ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --scope manglekuo-s-team --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy
        run: vercel deploy --prebuilt ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} --scope manglekuo-s-team --token=${{ secrets.VERCEL_TOKEN }}
